# Generated by Django 5.0.3 on 2024-03-27 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Direccion',
            new_name='Direction',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='direction',
            old_name='cliente',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='direction',
            old_name='ubicacion',
            new_name='location',
        ),
    ]
